- hosts: all
#  serial: 10
  tasks:
    - name: Upgrade Debian-Family
      apt: upgrade=yes update_cache=yes
      when: ansible_os_family == 'Debian'
      become: yes

    - name: Upgrade Centos-Family
      yum: name='*' update_only=yes update_cache=yes
      when: ansible_os_family == 'RedHat'
      become: yes
